CREATE TABLE IF NOT EXISTS produto (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(500),
    preco NUMERIC(10, 2),
    estoque INTEGER
    );