spring.application.name=config-server
server.port=9999
eureka.client.serviceUrl.defaultZone=http://localhost:9080/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.profiles.active=native

spring.cloud.config.server.native.search-locations=file:///home/vinicius/Área de trabalho/Engenharia de Software/Infnet/5 Semestre/2 Trimestre/Spring e Cloud/TPs/TP2/TP1_SPRING_CLOUD_MICROSERVICOS/Config.server/config-repo